[project]
# THE FIX: This line has been removed. 
# We do not want to prompt the user for this variable in the UI.
# user_env = ["OLLAMA_MODEL"]

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

# Authorized origins
allow_origins = ["*"]

[features]
unsafe_allow_html = false
latex = false
user_message_autoscroll = true
auto_tag_thread = true
edit_message = true

[features.spontaneous_file_upload]
    enabled = true
    accept = ["*/*"]
    max_files = 20
    max_size_mb = 500

[UI]
name = "David"
default_expand_messages = true
cot = "full"

[meta]
generated_by = "2.6.5"
