# Chainlit Configuration - Compatible with Phase 3 and Phase 4
[project]
enable_telemetry = true

[UI]
name = "David AI"
description = "Functionally conscious AI with multi-agent architecture"
cot = "full"
default_theme = "dark"
show_readme_as_default = true
collapse_message_input_on_send = false
hide_cot = false

[meta]
generated_by = "1.1.0"
